# GitHub Actions workflow for building Android app (React Native/Expo example)
# Adjust as needed for your stack (e.g., Capacitor, Cordova, etc.)

name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # If using Expo, you can use expo-github-action
      # - name: Install Expo CLI
      #   run: npm install -g expo-cli

      # - name: Build Android APK
      #   run: expo build:android --non-interactive

      # If using React Native CLI, set up Android SDK and build
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android app (if using React Native CLI)
        run: |
          cd android
          ./gradlew assembleRelease
        continue-on-error: true

      # Upload APK as artifact (if built)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
        if: success() || failure()
